package org.purpurmc.purpur.client.config;

import org.purpurmc.purpur.client.entity.Mob;
import org.purpurmc.purpur.client.entity.Seat;
import org.spongepowered.configurate.objectmapping.ConfigSerializable;

@ConfigSerializable
@SuppressWarnings("CanBeFinal")
public class Seats {
    public Seat axolotl = new Seat(0.0D, 0.0D, 0.0D);
    public Seat armadillo = new Seat(0.0D, 0.0D, 0.0D);
    public Seat allay = new Seat(0.0D, 0.0D, 0.0D);
    public Seat bat = new Seat(0.0D, 0.0D, 0.0D);
    public Seat bee = new Seat(0.0D, 0.0D, 0.0D);
    public Seat blaze = new Seat(0.0D, 0.0D, 0.0D);
    public Seat bogged = new Seat(0.0D, 0.0D, 0.0D);
    public Seat breeze = new Seat(0.0D, 0.0D, 0.0D);
    public Seat camel = new Seat(0.0D, 0.0D, 0.0D);
    public Seat cat = new Seat(0.0D, 0.0D, 0.0D);
    public Seat caveSpider = new Seat(0.0D, 0.0D, 0.0D);
    public Seat chicken = new Seat(0.0D, 0.0D, 0.0D);
    public Seat cod = new Seat(0.0D, 0.0D, 0.0D);
    public Seat cow = new Seat(0.0D, 0.0D, 0.0D);
    public Seat creeper = new Seat(0.0D, 0.0D, 0.0D);
    public Seat dolphin = new Seat(0.0D, 0.0D, 0.0D);
    public Seat donkey = new Seat(0.0D, 0.0D, 0.0D);
    public Seat drowned = new Seat(0.0D, 0.0D, 0.0D);
    public Seat elderGuardian = new Seat(0.0D, 0.0D, 0.0D);
    public Seat enderDragon = new Seat(0.0D, 0.0D, 0.0D);
    public Seat enderman = new Seat(0.0D, 0.0D, 0.0D);
    public Seat endermite = new Seat(0.0D, 0.0D, 0.0D);
    public Seat evoker = new Seat(0.0D, 0.0D, 0.0D);
    public Seat fox = new Seat(0.0D, 0.0D, 0.0D);
    public Seat frog = new Seat(0.0D, 0.0D, 0.0D);
    public Seat ghast = new Seat(0.0D, 0.0D, 0.0D);
    public Seat giant = new Seat(0.0D, 0.0D, 0.0D);
    public Seat glowSquid = new Seat(0.0D, 0.0D, 0.0D);
    public Seat goat = new Seat(0.0D, 0.0D, 0.0D);
    public Seat guardian = new Seat(0.0D, 0.0D, 0.0D);
    public Seat hoglin = new Seat(0.0D, 0.0D, 0.0D);
    public Seat horse = new Seat(0.0D, 0.0D, 0.0D);
    public Seat husk = new Seat(0.0D, 0.0D, 0.0D);
    public Seat illusioner = new Seat(0.0D, 0.0D, 0.0D);
    public Seat ironGolem = new Seat(0.0D, 0.0D, 0.0D);
    public Seat llama = new Seat(0.0D, 0.0D, 0.0D);
    public Seat magmaCube = new Seat(0.0D, 0.0D, 0.0D);
    public Seat mooshroom = new Seat(0.0D, 0.0D, 0.0D);
    public Seat mule = new Seat(0.0D, 0.0D, 0.0D);
    public Seat ocelot = new Seat(0.0D, 0.0D, 0.0D);
    public Seat panda = new Seat(0.0D, 0.0D, 0.0D);
    public Seat parrot = new Seat(0.0D, 0.0D, 0.0D);
    public Seat phantom = new Seat(0.0D, 0.0D, 0.0D);
    public Seat pig = new Seat(0.0D, 0.0D, 0.0D);
    public Seat piglin = new Seat(0.0D, 0.0D, 0.0D);
    public Seat piglinBrute = new Seat(0.0D, 0.0D, 0.0D);
    public Seat pillager = new Seat(0.0D, 0.0D, 0.0D);
    public Seat polarBear = new Seat(0.0D, 0.0D, 0.0D);
    public Seat pufferfish = new Seat(0.0D, 0.0D, 0.0D);
    public Seat rabbit = new Seat(0.0D, 0.0D, 0.0D);
    public Seat ravager = new Seat(0.0D, 0.0D, 0.0D);
    public Seat salmon = new Seat(0.0D, 0.0D, 0.0D);
    public Seat sheep = new Seat(0.0D, 0.0D, 0.0D);
    public Seat shulker = new Seat(0.0D, 0.0D, 0.0D);
    public Seat silverfish = new Seat(0.0D, 0.0D, 0.0D);
    public Seat skeleton = new Seat(0.0D, 0.0D, 0.0D);
    public Seat skeletonHorse = new Seat(0.0D, 0.0D, 0.0D);
    public Seat slime = new Seat(0.0D, 0.0D, 0.0D);
    public Seat snowGolem = new Seat(0.0D, 0.0D, 0.0D);
    public Seat spider = new Seat(0.0D, 0.0D, 0.0D);
    public Seat squid = new Seat(0.0D, 0.0D, 0.0D);
    public Seat stray = new Seat(0.0D, 0.0D, 0.0D);
    public Seat strider = new Seat(0.0D, 0.0D, 0.0D);
    public Seat tadpole = new Seat(0.0D, 0.0D, 0.0D);
    public Seat traderLlama = new Seat(0.0D, 0.0D, 0.0D);
    public Seat tropicalFish = new Seat(0.0D, 0.0D, 0.0D);
    public Seat turtle = new Seat(0.0D, 0.0D, 0.0D);
    public Seat vex = new Seat(0.0D, 0.0D, 0.0D);
    public Seat villager = new Seat(0.0D, 0.0D, 0.0D);
    public Seat vindicator = new Seat(0.0D, 0.0D, 0.0D);
    public Seat wanderingTrader = new Seat(0.0D, 0.0D, 0.0D);
    public Seat warden = new Seat(0.0D, 0.0D, 0.0D);
    public Seat witch = new Seat(0.0D, 0.0D, 0.0D);
    public Seat wither = new Seat(0.0D, 0.0D, 0.0D);
    public Seat witherSkeleton = new Seat(0.0D, 0.0D, 0.0D);
    public Seat wolf = new Seat(0.0D, 0.0D, 0.0D);
    public Seat zoglin = new Seat(0.0D, 0.0D, 0.0D);
    public Seat zombie = new Seat(0.0D, 0.0D, 0.0D);
    public Seat zombieHorse = new Seat(0.0D, 0.0D, 0.0D);
    public Seat zombieVillager = new Seat(0.0D, 0.0D, 0.0D);
    public Seat zombifiedPiglin = new Seat(0.0D, 0.0D, 0.0D);

    public void setAllSeats(double x, double y, double z) {
        allay.setSeat(z, y, z);
        armadillo.setSeat(z, y, z);
        axolotl.setSeat(z, y, z);
        bat.setSeat(z, y, z);
        bee.setSeat(z, y, z);
        blaze.setSeat(z, y, z);
        bogged.setSeat(z, y, z);
        breeze.setSeat(z, y, z);
        camel.setSeat(z, y, z);
        cat.setSeat(z, y, z);
        caveSpider.setSeat(z, y, z);
        chicken.setSeat(z, y, z);
        cod.setSeat(z, y, z);
        cow.setSeat(z, y, z);
        creeper.setSeat(z, y, z);
        dolphin.setSeat(z, y, z);
        donkey.setSeat(z, y, z);
        drowned.setSeat(z, y, z);
        elderGuardian.setSeat(z, y, z);
        enderDragon.setSeat(z, y, z);
        enderman.setSeat(z, y, z);
        endermite.setSeat(z, y, z);
        evoker.setSeat(z, y, z);
        fox.setSeat(z, y, z);
        frog.setSeat(z, y, z);
        ghast.setSeat(z, y, z);
        giant.setSeat(z, y, z);
        glowSquid.setSeat(z, y, z);
        goat.setSeat(z, y, z);
        guardian.setSeat(z, y, z);
        hoglin.setSeat(z, y, z);
        horse.setSeat(z, y, z);
        husk.setSeat(z, y, z);
        illusioner.setSeat(z, y, z);
        ironGolem.setSeat(z, y, z);
        llama.setSeat(z, y, z);
        magmaCube.setSeat(z, y, z);
        mooshroom.setSeat(z, y, z);
        mule.setSeat(z, y, z);
        ocelot.setSeat(z, y, z);
        panda.setSeat(z, y, z);
        parrot.setSeat(z, y, z);
        phantom.setSeat(z, y, z);
        pig.setSeat(z, y, z);
        piglin.setSeat(z, y, z);
        piglinBrute.setSeat(z, y, z);
        pillager.setSeat(z, y, z);
        polarBear.setSeat(z, y, z);
        pufferfish.setSeat(z, y, z);
        rabbit.setSeat(z, y, z);
        ravager.setSeat(z, y, z);
        salmon.setSeat(z, y, z);
        sheep.setSeat(z, y, z);
        shulker.setSeat(z, y, z);
        silverfish.setSeat(z, y, z);
        skeleton.setSeat(z, y, z);
        skeletonHorse.setSeat(z, y, z);
        slime.setSeat(z, y, z);
        snowGolem.setSeat(z, y, z);
        spider.setSeat(z, y, z);
        squid.setSeat(z, y, z);
        stray.setSeat(z, y, z);
        strider.setSeat(z, y, z);
        tadpole.setSeat(z, y, z);
        traderLlama.setSeat(z, y, z);
        tropicalFish.setSeat(z, y, z);
        turtle.setSeat(z, y, z);
        vex.setSeat(z, y, z);
        villager.setSeat(z, y, z);
        vindicator.setSeat(z, y, z);
        wanderingTrader.setSeat(z, y, z);
        warden.setSeat(z, y, z);
        witch.setSeat(z, y, z);
        wither.setSeat(z, y, z);
        witherSkeleton.setSeat(z, y, z);
        wolf.setSeat(z, y, z);
        zoglin.setSeat(z, y, z);
        zombie.setSeat(z, y, z);
        zombieHorse.setSeat(z, y, z);
        zombieVillager.setSeat(z, y, z);
        zombifiedPiglin.setSeat(z, y, z);
    }

    public Seat getSeat(Mob mob) {
        return switch (mob) {
            case ALLAY -> this.allay;
            case ARMADILLO -> this.armadillo;
            case AXOLOTL -> this.axolotl;
            case BAT -> this.bat;
            case BEE -> this.bee;
            case BLAZE -> this.blaze;
            case BOGGED -> this.bogged;
            case BREEZE -> this.breeze;
            case CAMEL -> this.camel;
            case CAT -> this.cat;
            case CAVE_SPIDER -> this.caveSpider;
            case CHICKEN -> this.chicken;
            case COD -> this.cod;
            case COW -> this.cow;
            case CREEPER -> this.creeper;
            case DOLPHIN -> this.dolphin;
            case DONKEY -> this.donkey;
            case DROWNED -> this.drowned;
            case ELDER_GUARDIAN -> this.elderGuardian;
            case ENDER_DRAGON -> this.enderDragon;
            case ENDERMAN -> this.enderman;
            case ENDERMITE -> this.endermite;
            case EVOKER -> this.evoker;
            case FOX -> this.fox;
            case FROG -> this.frog;
            case GHAST -> this.ghast;
            case GIANT -> this.giant;
            case GLOW_SQUID -> this.glowSquid;
            case GOAT -> this.goat;
            case GUARDIAN -> this.guardian;
            case HOGLIN -> this.hoglin;
            case HORSE -> this.horse;
            case HUSK -> this.husk;
            case ILLUSIONER -> this.illusioner;
            case IRON_GOLEM -> this.ironGolem;
            case LLAMA -> this.llama;
            case MAGMA_CUBE -> this.magmaCube;
            case MOOSHROOM -> this.mooshroom;
            case MULE -> this.mule;
            case OCELOT -> this.ocelot;
            case PANDA -> this.panda;
            case PARROT -> this.parrot;
            case PHANTOM -> this.phantom;
            case PIG -> this.pig;
            case PIGLIN_BRUTE -> this.piglinBrute;
            case PIGLIN -> this.piglin;
            case PILLAGER -> this.pillager;
            case POLAR_BEAR -> this.polarBear;
            case PUFFERFISH -> this.pufferfish;
            case RABBIT -> this.rabbit;
            case RAVAGER -> this.ravager;
            case SALMON -> this.salmon;
            case SHEEP -> this.sheep;
            case SHULKER -> this.shulker;
            case SILVERFISH -> this.silverfish;
            case SKELETON -> this.skeleton;
            case SKELETON_HORSE -> this.skeletonHorse;
            case SLIME -> this.slime;
            case SNOW_GOLEM -> this.snowGolem;
            case SPIDER -> this.spider;
            case SQUID -> this.squid;
            case STRAY -> this.stray;
            case STRIDER -> this.strider;
            case TADPOLE -> this.tadpole;
            case TRADER_LLAMA -> this.traderLlama;
            case TROPICAL_FISH -> this.tropicalFish;
            case TURTLE -> this.turtle;
            case VEX -> this.vex;
            case VILLAGER -> this.villager;
            case VINDICATOR -> this.vindicator;
            case WANDERING_TRADER -> this.wanderingTrader;
            case WARDEN -> this.warden;
            case WITCH -> this.witch;
            case WITHER -> this.wither;
            case WITHER_SKELETON -> this.witherSkeleton;
            case WOLF -> this.wolf;
            case ZOGLIN -> this.zoglin;
            case ZOMBIE -> this.zombie;
            case ZOMBIE_HORSE -> this.zombieHorse;
            case ZOMBIE_VILLAGER -> this.zombieVillager;
            case ZOMBIFIED_PIGLIN -> this.zombifiedPiglin;
        };
    }
}
