package org.purpurmc.purpur.client.config;

import org.purpurmc.purpur.client.entity.Mob;
import org.purpurmc.purpur.client.entity.Seat;
import org.spongepowered.configurate.objectmapping.ConfigSerializable;

@ConfigSerializable
public class Seats {
    public Seat bat = new Seat(-0.25D, 0.5D, 0.0D);
    public Seat bee = new Seat(-0.1D, 0.5D, 0.0D);
    public Seat cat = new Seat(0.0D, 0.4D, 0.0D);
    public Seat cod = new Seat(-0.25D, 0.1D, 0.0D);
    public Seat elderGuardian = new Seat(0.0D, 0.75D, 0.0D);
    public Seat enderDragon = new Seat(0.0D, 0.4D, 0.0D);
    public Seat fox = new Seat(-0.25D, 0.6D, 0.0D);
    public Seat hoglin = new Seat(0.0D, 0.75D, 0.0D);
    public Seat ironGolem = new Seat(-0.25D, 0.7D, 0.0D);
    public Seat ocelot = new Seat(0.0D, 0.5D, 0.0D);
    public Seat parrot = new Seat(-0.15D, 0.3D, 0.0D);
    public Seat piglin = new Seat(0.0D, 0.75D, 0.0D);
    public Seat piglinBrute = new Seat(0.0D, 0.75D, 0.0D);
    public Seat polarBear = new Seat(0.0D, 0.75D, 0.0D);
    public Seat pufferfish = new Seat(-0.1D, 0.25D, 0.0D);
    public Seat rabbit = new Seat(-0.25D, 0.4D, 0.0D);
    public Seat salmon = new Seat(-0.1D, 0.5D, 0.0D);
    public Seat snowGolem = new Seat(-0.3D, 0.6D, 0.0D);
    public Seat tropicalFish = new Seat(-0.1D, 0.7D, 0.0D);

    public Seat getSeat(Mob mob) {
        return switch (mob) {
            case AXOLOTL -> null;
            case BAT -> this.bat;
            case BEE -> this.bee;
            case BLAZE -> null;
            case CAT -> this.cat;
            case CAVE_SPIDER -> null;
            case CHICKEN -> null;
            case COD -> this.cod;
            case COW -> null;
            case CREEPER -> null;
            case DOLPHIN -> null;
            case DONKEY -> null;
            case DROWNED -> null;
            case ELDER_GUARDIAN -> this.elderGuardian;
            case ENDER_DRAGON -> this.enderDragon;
            case ENDERMAN -> null;
            case ENDERMITE -> null;
            case EVOKER -> null;
            case FOX -> this.fox;
            case GHAST -> null;
            case GIANT -> null;
            case GLOW_SQUID -> null;
            case GOAT -> null;
            case GUARDIAN -> null;
            case HOGLIN -> this.hoglin;
            case HORSE -> null;
            case HUSK -> null;
            case ILLUSIONER -> null;
            case IRON_GOLEM -> this.ironGolem;
            case LLAMA -> null;
            case MAGMA_CUBE -> null;
            case MOOSHROOM -> null;
            case MULE -> null;
            case OCELOT -> this.ocelot;
            case PANDA -> null;
            case PARROT -> this.parrot;
            case PHANTOM -> null;
            case PIG -> null;
            case PIGLIN_BRUTE -> this.piglinBrute;
            case PIGLIN -> this.piglin;
            case PILLAGER -> null;
            case POLAR_BEAR -> this.polarBear;
            case PUFFERFISH -> this.pufferfish;
            case RABBIT -> this.rabbit;
            case RAVAGER -> null;
            case SALMON -> this.salmon;
            case SHEEP -> null;
            case SHULKER -> null;
            case SILVERFISH -> null;
            case SKELETON -> null;
            case SKELETON_HORSE -> null;
            case SLIME -> null;
            case SNOW_GOLEM -> this.snowGolem;
            case SPIDER -> null;
            case SQUID -> null;
            case STRAY -> null;
            case STRIDER -> null;
            case TRADER_LLAMA -> null;
            case TROPICAL_FISH -> this.tropicalFish;
            case TURTLE -> null;
            case VEX -> null;
            case VILLAGER -> null;
            case VINDICATOR -> null;
            case WANDERING_TRADER -> null;
            case WITCH -> null;
            case WITHER -> null;
            case WITHER_SKELETON -> null;
            case WOLF -> null;
            case ZOGLIN -> null;
            case ZOMBIE -> null;
            case ZOMBIE_HORSE -> null;
            case ZOMBIE_VILLAGER -> null;
            case ZOMBIFIED_PIGLIN -> null;
        };
    }
}
